## Lecture 3 - Programming Activity

### Activity 1 - Write a function that takes a filename as input.

You will be using the **bill_of_rights.txt** located in the **data** folder for this activity. Write a function that takes the filename as input and finds the total number of lines, words and most frequent word in the file and writes these statistics into a file named **‘stats.txt’**.

In [6]:
## Start Code

def nline(file):
    c = 0
    for line in file:
        c = file.readlines()
    print("Number of lines in file:", len(c))

with open("./data/bill_of_rights.txt","r") as f:
    nline(f);
    


## End Code

Number of lines in file: 53


### Activity 2 - Parse a file to produce a list

You will be using the file **gps.csv** located in the **data** folder for this activity. Parse the file and produce a list of coordinates (**lat** and **lon**) along with the **unix timestamp** of their visit.

In [13]:
## Start Code

import csv
def coord(file):
    f = csv.reader(file)
    for line in f:
        print(line[2:4])

with open("./data/gps.csv","r") as f:
    coord(f)


## End Code

['lat', 'long']
['40.78966141', '-77.85948515']
['40.78963995', '-77.85954952']
['40.78961849', '-77.85957098']
['40.78953266', '-77.85965681']
['40.78957558', '-77.85972118']
['40.78968287', '-77.85976410']
['40.78979015', '-77.85961390']
['40.78983307', '-77.85961390']
['40.78987598', '-77.85950661']
['40.78996181', '-77.85946369']
['40.79011202', '-77.85957098']
['40.79015493', '-77.85954952']
['40.79015493', '-77.85950661']
['40.79021931', '-77.85929203']
['40.79024076', '-77.85927057']
['40.79036951', '-77.85907745']
['40.79036951', '-77.85909891']
['40.79047680', '-77.85899162']
['40.79064846', '-77.85920620']
['40.79069138', '-77.85922766']
['40.79079866', '-77.85939932']
['40.79101324', '-77.85967827']
['40.79101324', '-77.85965681']
['40.79118490', '-77.85987139']
['40.79133511', '-77.86006451']
['40.79161406', '-77.85987139']
['40.79172134', '-77.85991430']
['40.79172134', '-77.85991430']
['40.79167843', '-77.86004305']
['40.79159260', '-77.86015034']
['40.79154968', '-77.860

### Activity 3

1. Create an array of 5 values between 5 to 10 and remove 1,2,4 index value from the array. 
2. Create an empty array having 10 values and assign half values as 10 and half of them as 20.
3. Write a function that takes as input a 2-D ndarray and scale the last row and column by 2.5.

In [37]:
# Start Code

import numpy as np
#First task
arr = np.arange(5,11)
print(arr)
arr= np.delete(arr,(1,2,4))
print(arr)

#Second task
v = np.empty(10)
v[:5] = 10
v[5:] = 20
print(v)

#Third task

def scale(vet):
    vet[-1] = vet[-1] * 2.5
    print(vet)

vv = np.array([[1.,2.],[3.,4.]])
scale(vv)

# End Code

[ 5  6  7  8  9 10]
[ 5  8 10]
[10. 10. 10. 10. 10. 20. 20. 20. 20. 20.]
[[ 1.   2. ]
 [ 7.5 10. ]]


### Activity 4

1. Write a function that takes a matrix as input and subtract the mean of each row of a matrix. 
2. Write a function to find the most frequent value in an array.
3. Write a function which creates an  n×n  array with  (i,j) entry equal to  i+j.


In [47]:
# Start Code

import numpy as np
from scipy import stats

#First task
def submean(vet):
    for i in range(vet.shape[0]):
        m = vet[i].mean()
        vet[i] = vet[i] - m
    print(vet)

v = np.array([[1,2,3],[4,5,6],[7,8,9]])
submean(v)

#Second task
def frequentv(vet):
    val = stats.mode(vet)
    print(f"Most frequent value is {val.mode[0]}\n")

vv = np.array([[2,2,2],[1,1,3],[1,2,1]])
frequentv(vv)

#Third task
def carray(vet):
    for i in range(vet.shape[0]):
        for j in range(vet.shape[0]):
            vet[i][j] = i+j
    print(vet)
vvv = np.empty([3,3])
carray(vvv)
    
#End Code

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
Most frequent value is 1

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


### Activity 5

Using the ‘titanic_data_sample' using pandas.

1. Find and print top 5 and bottom 5 rows from the data.
2. Find the descriptive statistics of age and fare of all passengers.
3. Extract passengers who age is below 25 and have survived.
4. Extract the number of Female Passengers over 25 and in 1st class.

In [ ]:
# Start Code



# End Code